# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from pathlib import Path
from datetime import date
class TestTestteslaCihazlar1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.folderPath = str(date.today())
    Path(self.folderPath).mkdir(exist_ok=True)
  
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testteslaCihazlar1(self):
    self.driver.get("https://www.tesla.com/tr_tr")
    self.driver.set_window_size(1552, 832)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#dx-nav-item--energy > .tds-site-nav-item-text")))
    self.driver.find_element(By.CSS_SELECTOR, "#dx-nav-item--energy > .tds-site-nav-item-text").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "Cihazlar")))
    self.driver.find_element(By.LINK_TEXT, "Cihazlar").click()
    time.sleep(2)
    self.driver.save_screenshot(f"{self.folderPath}/test-Cihazlar.png")
    self.driver.execute_script("window.scrollTo(0,6200)")
    
    time.sleep(2)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "firstName")))
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "lastName")))
    self.driver.find_element(By.NAME, "lastName").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "email")))
    self.driver.find_element(By.NAME, "email").send_keys("test@hotmail.com")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "street1")))
    self.driver.find_element(By.NAME, "street1").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "city")))
    self.driver.find_element(By.NAME, "city").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "state")))
    self.driver.find_element(By.NAME, "state").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "zip")))
    self.driver.find_element(By.NAME, "zip").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "companyName")))
    self.driver.find_element(By.NAME, "companyName").send_keys("test")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "enterprise")))
    self.driver.find_element(By.NAME, "enterprise").send_keys("test")
    self.driver.execute_script("window.scrollTo(7000,7100)")
    

    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.NAME, "notes")))
    self.driver.find_element(By.NAME, "notes").send_keys("test")
    time.sleep(2)
    self.driver.save_screenshot(f"{self.folderPath}/test-CihazlarForm.png")

    
    
 
    

  
